---
- name: Install qemu-guest-agent
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Fail if not Debian family
      ansible.builtin.fail:
        msg: "This playbook is only for hosts with apt."
      when: ansible_facts["os_family"] | lower != "debian"

    - name: Install qemu-guest-agent
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present
        update_cache: true
        cache_valid_time: 3600

- name: Prepare image for VM template
  hosts: all
  become: true
  roles:
    - role: template-prep
