name: ci

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - name: Setup packer
        uses: hashicorp/setup-packer@76e3039aa951aa4e6efe7e6ee06bc9ceb072142d
        id: setup
        with:
          version: latest

      - name: Run `packer init`
        id: init
        run: "packer init ."

      - name: Run `packer fmt`
        id: format
        run: "packer fmt --recursive --check --diff --write=false ."

      - name: Run `packer validate` (syntax)
        id: validate
        run: "packer validate --no-warn-undeclared-var --syntax-only ."
